### ISSUE TITLE
Create Django 2.0 roadmap

### ISSUE THREAD

**Issue by lizzard** [lizzard/hg-to-git#5]
- [x] Early estimates and outline in hg/git migration meetup doc
- [x] Initial roadmap in zeid's spreadsheet
- [ ] Whatever I'm doing to map things in github/zenhub projects
